# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/items', type: :request do
  let(:company) { create(:company) }
  let(:item) { create(:item, company: company) }

  describe 'GET /index' do
    it 'renders the index page successfully' do
      get items_path
      expect(response).to have_http_status(:ok)
    end
  end

  describe 'GET /show' do
    it 'renders the show page successfully' do
      get item_path(item)
      expect(response).to have_http_status(:ok)
    end
  end

  describe 'GET /new' do
    it 'renders the new page successfully' do
      get new_item_path
      expect(response).to have_http_status(:ok)
    end
  end

  describe 'GET /edit' do
    it 'renders the edit page successfully' do
      get edit_item_path(item)
      expect(response).to have_http_status(:ok)
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      let(:valid_params) { { item: { name: 'New Item', vat: 16, company_id: company.id } } }

      it 'creates a new item and redirects' do
        expect do
          post items_path, params: valid_params
        end.to change(Item, :count).by(1)

        expect(response).to redirect_to(item_path(Item.last))
        follow_redirect!
        expect(response.body).to include('Item was successfully created.')
      end
    end

    context 'with invalid parameters' do
      let(:invalid_params) { { item: { name: '', vat: nil, company_id: nil } } }

      it 'does not create an item and renders new template' do
        expect do
          post items_path, params: invalid_params
        end.not_to change(Item, :count)

        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:update_params) { { item: { name: 'Updated Item' } } }

      it 'updates the item and redirects' do
        patch item_path(item), params: update_params
        expect(response).to redirect_to(item_path(item))
        follow_redirect!
        expect(response.body).to include('Item was successfully updated.')
        expect(item.reload.name).to eq('Updated Item')
      end
    end

    context 'with invalid parameters' do
      let(:invalid_update_params) { { item: { name: '' } } }

      it 'does not update the item and renders edit template' do
        patch item_path(item), params: invalid_update_params
        expect(response).to have_http_status(:unprocessable_entity)
        expect(item.reload.name).not_to eq('')
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'deletes the item and redirects to index' do
      item # ensure item exists before deletion
      expect do
        delete item_path(item)
      end.to change(Item, :count).by(-1)

      expect(response).to redirect_to(items_path)
      follow_redirect!
    end
  end
end
