require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.


RSpec.describe "/transactions", type: :request do
  let(:user) { create(:user) }
  let(:customer) { create(:customer) }
  let(:transaction) { create(:transaction, user: user, customer: customer) }

  describe "GET /index" do
    it "renders the index page successfully" do
      get transactions_path
      expect(response).to have_http_status(:ok)
    end

    it "renders CSV format" do
      get transactions_path(format: :csv)
      expect(response).to have_http_status(:ok)
      expect(response.headers['Content-Type']).to include('text/csv')
    end
  end

  describe "GET /show" do
    it "renders the show page successfully" do
      get transaction_path(transaction)
      expect(response).to have_http_status(:ok)
    end
  end

  describe "GET /new" do
    it "renders the new page successfully" do
      get new_transaction_path
      expect(response).to have_http_status(:ok)
    end
  end

  describe "GET /edit" do
    it "renders the edit page successfully" do
      get edit_transaction_path(transaction)
      expect(response).to have_http_status(:ok)
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      let(:valid_params) do
        {
          transaction: {
            user_id: user.id,
            customer_id: customer.id,
            deals_attributes: [
              { price: 100, quantity: 2, item_id: create(:item).id }
            ]
          }
        }
      end
    end

    context "with invalid parameters" do
      let(:invalid_params) { { transaction: { user_id: nil, customer_id: nil } } }

      it "does not create a transaction and renders new template" do
        expect {
          post transactions_path, params: invalid_params
        }.not_to change(Transaction, :count)

        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.body).to include("prohibited this transaction from being saved")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:update_params) { { transaction: { customer_id: create(:customer).id } } }

      it "updates the transaction and redirects" do
        patch transaction_path(transaction), params: update_params
        expect(response).to redirect_to(transaction_path(transaction))
        follow_redirect!
      end
    end

    context "with invalid parameters" do
      let(:invalid_update_params) { { transaction: { customer_id: nil } } }

      it "does not update the transaction and renders edit template" do
        patch transaction_path(transaction), params: invalid_update_params
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.body).to include("prohibited this transaction from being saved")
      end
    end
  end

  describe "DELETE /destroy" do
    it "deletes the transaction and redirects to index" do
      transaction # Ensure transaction exists before deletion
      expect {
        delete transaction_path(transaction)
      }.to change(Transaction, :count).by(-1)

      expect(response).to redirect_to(transactions_path)
      follow_redirect!
    end
  end

  describe "GET /summary" do
    it "renders the summary page successfully" do
      get summary_transactions_path
      expect(response).to have_http_status(:ok)
    end
  end
end

